name: pokedex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: PokemonSolid
      fonts:
        - asset: assets/fonts/PokemonSolid.ttf
    - family: PokemonHollow
      fonts:
        - asset: assets/fonts/PokemonHollow.ttf